### PR TITLE
Design fix

### PR DESCRIPTION
**Pull request by odgaard**
_**The big update**_

us19, tech5 and design improvements.

All 33 tests passing, with 91% coverage

Manually tested:
Login, Join different lectures and confirming different rooms. Feedback for each room. Voting on messages.  Leave rooms. Logout.

Code reviewed, and it looks fine.

### CODE REVIEW

**Comment by weedle1912** [comment]
This branch also includes us5 (back-end) and us6 (voting and sorting based on votes), to be accurate. 

Per our branching model, the proper timeline should be "design-fix -> us19" and then "us19 -> develop", but this is probably the easier way? :)

**Comment by odgaard** [comment]
Well, I consider this a continuation of the mentioned user stories. Which is why this branch could be merged, instead of the "base" branch. Still seems like we have a problem with the branch requiring a rebase, due  to changes in develop. I'll be taking a look at it now.

**Comment by odgaard** [comment]
Everything in the root folder and in the server folder has been code reviewed by me. 
Still need a code review of front-end ( src/client ) from a front-end dev. 
@frozenlight @teatimes

**Review by oleast — APPROVED** [review]
Reviewed, approved frontend and backend.

Fixed filtering frontend filtering of the LectureTable, because it was done only half way.

**Review by weedle1912 — APPROVED** [review]
Reviewed front-end.

**Pull request merged**
